# Generated by Django 3.2.15 on 2023-03-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FillteringApp', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
